using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;
using UnityFigmaBridge.Editor.Utils;

namespace UnityFigmaBridge.Editor.Extension.Generator
{
    /// <summary>
    /// コマンドキー 一覧定義スクリプト作成用
    /// </summary>
    public class CommandKeyListCodeGenerator
    {
        public static void WriteCommandKeyListCodeFile(string fileName, HashSet<string> commandKeyList)
        {
            fileName = Capitalize(fileName);
            var className = fileName + "CommandKey";
            var outputPath = $"{FigmaPaths.FigmaAssetsRootFolder}/{className}.cs";
            
            var content = $@"
// Automatically generated by UnityFigmaBridge

namespace {fileName}.Utility
{{
    public class {className}
    {{
";
            foreach (var commandKey in commandKeyList)
            {
                var variableName = Capitalize(GetLastPart(commandKey));
                content += $"\t\tpublic static readonly string {variableName} = \"{commandKey}\";\n";
            }
            
            content+=@"
    }
}
";
            
            Debug.Log("コマンドキースクリプト生成");
            File.WriteAllText(outputPath, content);
            // Reimport
            AssetDatabase.ImportAsset(outputPath);
        }
        
        /// <summary>
        /// 先頭を大文字に
        /// </summary>
        public static string Capitalize(string s)
        {
            if (string.IsNullOrEmpty(s)) return s;
            return char.ToUpper(s[0]) + s.Substring(1);
        }

        /// <summary>
        /// 「.」ピリオド区切りで末尾だけ取得する
        /// </summary>
        public static string GetLastPart (string s)
        {
            int index = s.LastIndexOf('.');
            return index >= 0 ? s.Substring(index + 1) : s;
        }
    }
}